export default function Home() {
  return (
    <main className=''>
      <h2>Horario de este semestre</h2>

      <section className='mt-4'>
        <section className='grid grid-cols-6'>
          <div>Lunes</div>
          <div>Martes</div>
          <div>Miércoles</div>
          <div>Jueves</div>
          <div>Viernes</div>
          <div>Sábado</div>
          <div>
            <div>7:00 AM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>8:00 AM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>9:00 AM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>10:00 AM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>11:00 AM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>12:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>01:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>02:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>03:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>04:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>05:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>06:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>07:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>08:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>09:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>10:00 PM</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
          <div>
            <div>hora</div>
          </div>
        </section>
      </section>
    </main>
  )
}
